# Generated by rebar3_nix
let fetchOnly = { src, ... }: src;
in { builder ? fetchOnly, fetchHex, fetchgit, fetchFromGitHub, overrides ? (x: y: { }) }:
let
  self = packages // (overrides self packages);
  packages = with self; {
    enough = builder {
      name = "enough";
      version = "0.1.0";
      src = fetchHex {
        pkg = "enough";
        version = "0.1.0";
        sha256 = "sha256-BGDHq9pfXg6lkrErxpdrilxLluQvMyBZzTllJTdL+aE=";
      };
      beamDeps = [ ];
    };
    cowlib = builder {
      name = "cowlib";
      version = "2.12.1";
      src = fetchHex {
        pkg = "cowlib";
        version = "2.12.1";
        sha256 = "sha256-Fjtz9jZ6c0GzPHlMTojn2/5kmKxC3Nae9ExbxVB8jbA=";
      };
      beamDeps = [ ];
    };
    systemd = builder {
      name = "systemd";
      version = "git";
      src = fetchFromGitHub {
        owner = "hauleth";
        repo = "erlang-systemd";
        rev = "bd5f82497c84a3e4228703ca18105de7ff0d0244";
        sha256 = "1w8lav98zndzgyrj0nbqbx9inv4ns114bvka0vrcpvm9q2wd6i6q";
      };
      beamDeps = [ enough ];
    };
    ranch = builder {
      name = "ranch";
      version = "2.1.0";
      src = fetchHex {
        pkg = "ranch";
        version = "2.1.0";
        sha256 = "sha256-JE7j+iphdScNjh/FkCT9nbx2KUoyEFfej4A7FHnnaRY=";
      };
      beamDeps = [ ];
    };
    msgpack = builder {
      name = "msgpack";
      version = "git";
      src = fetchFromGitHub {
        owner = "tomjnixon";
        repo = "msgpack-erlang";
        rev = "5387b780e7727d8002b49e2ca2514c19296b6d80";
        sha256 = "1crakn55i3sfjxnlrr27ns3rf23z6nwzgy1si1klc19wsdz66503";
      };
      beamDeps = [ ];
    };
    jiffy = builder {
      name = "jiffy";
      version = "1.1.1";
      src = fetchHex {
        pkg = "jiffy";
        version = "1.1.1";
        sha256 = "sha256-YuHwWBw8GcM6clx4HfqIQQ2L/xu6/DiFolUihrR4XEw=";
      };
      beamDeps = [ ];
    };
    eshet = builder {
      name = "eshet";
      version = "git";
      src = fetchFromGitHub {
        owner = "tomjnixon";
        repo = "eshet";
        rev = "4c9de686129066d9f28bcf1c26e4eb00d9257182";
        sha256 = "0s548hp2h2mi52l6949p3hcjqrngd61sg1z2dwjv7bxvncmxkrb1";
      };
      beamDeps = [ ];
    };
    cowboy = builder {
      name = "cowboy";
      version = "2.10.0";
      src = fetchHex {
        pkg = "cowboy";
        version = "2.10.0";
        sha256 = "sha256-Ov3Mtxg8xvFDyxTTz1H6AOU9ueyAzc1SVIL16ZvEHWs=";
      };
      beamDeps = [ cowlib ranch ];
    };
    gun = builder {
      name = "gun";
      version = "2.0.1";
      src = fetchHex {
        pkg = "gun";
        version = "2.0.1";
        sha256 = "sha256-oQvI1glrlQIgUCIzT3GcyaCNmtz7/A2+6e8xtWJ0ogs=";
      };
      beamDeps = [ cowlib ];
    };
  };
in self
