PROJECT = eshethttp
PROJECT_DESCRIPTION = HTTP interface for eshet
PROJECT_VERSION = 0.1.0

dep_cowboy_commit = 2.7.0
dep_ranch_commit = 1.7.1
dep_cowlib_commit = 2.9.1

DEPS = eshet cowboy jiffy
LOCAL_DEPS = eshetproto

include ../../erlang.mk
