PROJECT = eshetproto
PROJECT_DESCRIPTION = New project
PROJECT_VERSION = 0.1.0

dep_ranch_commit = 1.7.1
dep_msgpack = git https://github.com/tomjnixon/msgpack-erlang pack_unpack_binary
DEPS = eshet ranch msgpack

include ../../erlang.mk
